import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'

import { Toaster } from '@/components/ui/sonner'

import '@/styles/globals.css'

const nunito = Nunito({
  subsets: ['latin'],
  variable: '--font-noto-sans',
  display: 'swap',
  weight: ['400', '500', '700', '900']
})

export const metadata: Metadata = {
  title: 'Blockito | Ofertas laborales',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='es'>
      <body className={`${nunito.className} antialiased`}>
        {children}

        <Toaster />
      </body>
    </html>
  )
}
